"""
Sign-Language Model Training Script
Trains sign-language models (Random Forest or MLP) with optional
data augmentation and K-fold cross-validation.

Usage:
    # Train Random Forest (default)
    python scripts/train_model.py --input data/processed --output models/asl_alphabet.pkl

    # Train MLP neural network
    python scripts/train_model.py --input data/processed --output models/asl_mlp.pkl \\
        --model-type mlp

    # Train with data augmentation and K-fold cross-validation
    python scripts/train_model.py --input data/processed --output models/asl_alphabet.pkl \\
        --augment --augment-factor 5 --cv-folds 5

Reference: PRD Section 8.3.2 (Training Pipeline)
"""

import sys
import argparse
import json
import numpy as np
import pickle
from pathlib import Path
from tqdm import tqdm
from datetime import datetime

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))
from gesture_platform.normalizer import Normalizer
from gesture_platform.feature_extractor import FeatureExtractor
from gesture_platform.augmentation import DataAugmentor
from gesture_platform.mlp_model import MLPRecognizer


def parse_mlp_hidden_layers(raw: str) -> tuple:
    """Parse comma-separated hidden layer sizes (e.g. '256,128')."""
    try:
        layers = tuple(int(x.strip()) for x in raw.split(",") if x.strip())
    except ValueError as exc:
        raise ValueError("Hidden layers must be comma-separated integers.") from exc
    if not layers or any(layer <= 0 for layer in layers):
        raise ValueError("Hidden layers must contain positive integers.")
    return layers


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Train sign-language model from processed dataset'
    )
    parser.add_argument(
        '--input',
        type=str,
        required=True,
        help='Input directory containing processed data'
    )
    parser.add_argument(
        '--output',
        type=str,
        required=True,
        help='Output path for trained model'
    )
    parser.add_argument(
        '--model-type',
        type=str,
        default='random_forest',
        choices=['random_forest', 'mlp'],
        help='Model architecture to train (default: random_forest)'
    )
    parser.add_argument(
        '--n-estimators',
        type=int,
        default=200,
        help='Number of trees in Random Forest (ignored for mlp)'
    )
    parser.add_argument(
        '--max-depth',
        type=int,
        default=30,
        help='Maximum depth of trees (ignored for mlp)'
    )
    parser.add_argument(
        '--mlp-hidden-layers',
        type=str,
        default='256,128',
        help='Comma-separated hidden layer sizes for MLP, e.g. "256,128"'
    )
    parser.add_argument(
        '--mlp-max-iter',
        type=int,
        default=500,
        help='Maximum training iterations for MLP (ignored for random_forest)'
    )
    parser.add_argument(
        '--test-size',
        type=float,
        default=0.2,
        help='Test set proportion'
    )
    parser.add_argument(
        '--normalize',
        action='store_true',
        help='Apply normalization to features'
    )
    parser.add_argument(
        '--cv-folds',
        type=int,
        default=5,
        help='Number of cross-validation folds (0 to skip)'
    )
    parser.add_argument(
        '--augment',
        action='store_true',
        help='Apply data augmentation to training set'
    )
    parser.add_argument(
        '--augment-factor',
        type=int,
        default=5,
        help='Augmented copies per original sample (used with --augment)'
    )
    parser.add_argument(
        '--augment-rotation',
        type=float,
        default=15.0,
        help='Max rotation in degrees for augmentation'
    )
    parser.add_argument(
        '--augment-noise',
        type=float,
        default=0.005,
        help='Gaussian noise std for augmentation'
    )
    parser.add_argument(
        '--random-seed',
        type=int,
        default=42,
        help='Random seed for reproducibility'
    )
    parser.add_argument(
        '--language-code',
        type=str,
        default=None,
        help='Optional language code override (e.g., ASL, NSL, BSL)'
    )
    parser.add_argument(
        '--language-name',
        type=str,
        default=None,
        help='Optional language display name override'
    )

    return parser.parse_args()


def load_dataset_manifest(data_dir: str):
    """Load optional dataset manifest generated by preprocess_dataset.py."""
    manifest_path = Path(data_dir) / 'dataset_manifest.json'
    if not manifest_path.exists():
        return None
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_dataset(data_dir: str):
    """
    Load preprocessed dataset.

    Args:
        data_dir: Directory containing processed data

    Returns:
        Tuple of (features, labels, class_names)
    """
    data_path = Path(data_dir)
    combined_file = data_path / 'combined_data.pkl'

    if not combined_file.exists():
        # Try to load individual files
        print(f"Loading individual files from {data_path}")
        pkl_files = list(data_path.glob('*.pkl'))
        pkl_files = [f for f in pkl_files if f.name != 'combined_data.pkl']
        print(f"Found {len(pkl_files)} files")

        loaded_samples = []
        for pkl_file in tqdm(pkl_files):
            with open(pkl_file, 'rb') as f:
                sample = pickle.load(f)
            loaded_samples.append((sample["class"], [sample]))
        return _extract_dataset_from_samples(loaded_samples)

    print(f"Loading dataset from {combined_file}")
    with open(combined_file, 'rb') as f:
        all_data = pickle.load(f)

    print(f"Processing {len(all_data)} classes...")
    return _extract_dataset_from_samples(all_data.items())


def _extract_dataset_from_samples(items):
    """Normalize and extract static features from class/sample items."""
    normalizer = Normalizer()
    feature_extractor = FeatureExtractor(include_velocity=False)
    features = []
    labels = []
    classes = set()

    for class_name, samples in tqdm(items):
        for sample in samples:
            landmarks = normalizer.normalize(sample["landmarks"])
            feat = feature_extractor.extract_static(landmarks)
            features.append(feat)
            labels.append(class_name)
            classes.add(class_name)

    return np.asarray(features), np.asarray(labels), sorted(classes)


def augment_training_data(
    X_train: np.ndarray,
    y_train: np.ndarray,
    feature_extractor: FeatureExtractor,
    num_augmentations: int = 5,
    rotation_range: float = 15.0,
    noise_std: float = 0.005,
    random_seed: int = 42
):
    """
    Apply data augmentation to raw landmark features.

    Augmentation is applied in landmark space when the input feature
    dimension is 63 (21 landmarks × 3 coordinates); otherwise the
    original data is returned unchanged.

    Args:
        X_train: Training features of shape (n_samples, n_features).
        y_train: Corresponding labels.
        feature_extractor: Used to re-extract features from augmented landmarks.
        num_augmentations: Number of augmented copies per sample.
        rotation_range: Max rotation in degrees.
        noise_std: Gaussian noise standard deviation.
        random_seed: Random seed for the augmentor.

    Returns:
        Tuple of augmented (X_train, y_train).
    """
    n_features = X_train.shape[1]
    # Only augment if features are raw landmark coordinates (21*3 = 63)
    if n_features != 63:
        print("Skipping augmentation: feature dimension is not 63 (raw landmarks).")
        return X_train, y_train

    augmentor = DataAugmentor(
        rotation_range=rotation_range,
        noise_std=noise_std,
        seed=random_seed,
    )

    X_aug_list = [X_train]
    y_aug_list = [y_train]

    print(f"Augmenting training data ({num_augmentations}× per sample)...")
    for i in tqdm(range(len(X_train))):
        lm = X_train[i].reshape(21, 3)
        augmented = augmentor.augment(lm, num_augmentations=num_augmentations)[1:]
        for aug_lm in augmented:
            feat = feature_extractor.extract_static(aug_lm)
            X_aug_list.append(feat.reshape(1, -1))
            y_aug_list.append(np.array([y_train[i]]))

    X_augmented = np.vstack(X_aug_list)
    y_augmented = np.concatenate(y_aug_list)
    print(f"  Original samples: {len(X_train)} → Augmented: {len(X_augmented)}")
    return X_augmented, y_augmented


def train_random_forest(
    X_train: np.ndarray,
    y_train: np.ndarray,
    n_estimators: int = 200,
    max_depth: int = 30,
    random_seed: int = 42
):
    """
    Train Random Forest model.

    Args:
        X_train: Training features
        y_train: Training labels
        n_estimators: Number of trees
        max_depth: Maximum tree depth
        random_seed: Random seed

    Returns:
        Trained RandomForestClassifier
    """
    print(f"\nTraining Random Forest with {n_estimators} trees...")

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=5,
        criterion='gini',
        random_state=random_seed,
        n_jobs=-1,  # Use all CPU cores
        verbose=1
    )

    model.fit(X_train, y_train)

    return model


def train_mlp(
    X_train: np.ndarray,
    y_train: np.ndarray,
    hidden_layer_sizes: tuple = (256, 128),
    max_iter: int = 500,
    random_seed: int = 42
):
    """
    Train MLP neural network model.

    Args:
        X_train: Training features
        y_train: Training labels
        hidden_layer_sizes: Hidden layer architecture
        max_iter: Maximum training iterations
        random_seed: Random seed

    Returns:
        Trained MLPRecognizer
    """
    print(f"\nTraining MLP with layers {hidden_layer_sizes}...")

    recognizer = MLPRecognizer(
        hidden_layer_sizes=hidden_layer_sizes,
        max_iter=max_iter,
        random_state=random_seed,
    )
    recognizer.train(X_train, y_train, verbose=True)
    return recognizer




def run_cross_validation(
    X: np.ndarray,
    y: np.ndarray,
    model_type: str,
    cv_folds: int = 5,
    random_seed: int = 42,
    n_estimators: int = 200,
    max_depth: int = 30,
    hidden_layer_sizes: tuple = (256, 128),
    max_iter: int = 500,
):
    """
    Run stratified K-fold cross-validation and report mean ± std accuracy.

    Args:
        X: Full feature matrix.
        y: Full label array.
        model_type: ``'random_forest'`` or ``'mlp'``.
        cv_folds: Number of folds.
        random_seed: Random seed.
        n_estimators: Trees for Random Forest.
        max_depth: Depth for Random Forest.
        hidden_layer_sizes: Architecture for MLP.
        max_iter: Max iterations for MLP.

    Returns:
        Dict with 'mean_accuracy' and 'std_accuracy'.
    """
    print(f"\nRunning {cv_folds}-fold cross-validation (model_type={model_type})...")

    skf = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=random_seed)
    fold_accuracies = []

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
        X_tr, X_val = X[train_idx], X[val_idx]
        y_tr, y_val = y[train_idx], y[val_idx]

        if model_type == 'mlp':
            recognizer = MLPRecognizer(
                hidden_layer_sizes=hidden_layer_sizes,
                max_iter=max_iter,
                random_state=random_seed,
            )
            recognizer.train(X_tr, y_tr, verbose=False)
            # Evaluate using predict_batch
            results = recognizer.predict_batch(X_val)
            y_pred = [cls if cls is not None else '__none__' for cls, _ in results]
        else:
            clf = RandomForestClassifier(
                n_estimators=n_estimators,
                max_depth=max_depth,
                min_samples_split=5,
                random_state=random_seed,
                n_jobs=-1,
            )
            clf.fit(X_tr, y_tr)
            y_pred = clf.predict(X_val)

        acc = accuracy_score(y_val, y_pred)
        fold_accuracies.append(acc)
        print(f"  Fold {fold}/{cv_folds}: {acc:.4f} ({acc*100:.2f}%)")

    mean_acc = float(np.mean(fold_accuracies))
    std_acc = float(np.std(fold_accuracies))
    print(f"\nCV Result: {mean_acc:.4f} ± {std_acc:.4f}  "
          f"({mean_acc*100:.2f}% ± {std_acc*100:.2f}%)")
    return {'mean_accuracy': mean_acc, 'std_accuracy': std_acc}


def evaluate_model(
    model,
    X_test: np.ndarray,
    y_test: np.ndarray,
    class_names: list,
    cv_folds: int = 5
):
    """
    Evaluate model performance.

    Args:
        model: Trained model (RandomForestClassifier or MLPRecognizer)
        X_test: Test features
        y_test: Test labels
        class_names: List of class names
        cv_folds: Number of CV folds (informational only; CV is run separately)

    Returns:
        Dictionary of metrics
    """
    print("\n" + "="*50)
    print("MODEL EVALUATION")
    print("="*50)

    # Support both RandomForestClassifier and MLPRecognizer interfaces
    if isinstance(model, MLPRecognizer):
        results = model.predict_batch(X_test)
        y_pred = [cls if cls is not None else '__none__' for cls, _ in results]
    else:
        y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    print(f"\nTest Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

    # Classification report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names))

    # Confusion matrix summary
    cm = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix Shape: {cm.shape}")

    # Highlight most-confused pairs
    np.fill_diagonal(cm, 0)
    confused_indices = np.unravel_index(np.argsort(cm, axis=None)[::-1][:5], cm.shape)
    print("\nTop confused letter pairs:")
    for i, j in zip(confused_indices[0], confused_indices[1]):
        if cm[i, j] > 0:
            print(f"  {class_names[i]} → {class_names[j]}: {cm[i, j]} errors")

    metrics = {
        'accuracy': accuracy,
        'n_classes': len(class_names),
        'n_test_samples': len(y_test)
    }

    return metrics


def save_model(
    model,
    class_names: list,
    output_path: str,
    accuracy: float = None,
    model_type: str = 'RandomForest',
    language_code: str = 'ASL',
    language_name: str = 'American Sign Language',
    dataset_name: str = 'unknown-dataset',
):
    """
    Save trained model.

    Args:
        model: Trained model
        class_names: List of class names
        output_path: Output file path
        accuracy: Optional accuracy for metadata
        model_type: Model type string for metadata
    """
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    if isinstance(model, MLPRecognizer):
        # MLPRecognizer has its own save method that stores the scaler too
        model.save(output_path)
        # Patch metadata into the saved file
        with open(output_file, 'rb') as f:
            data = pickle.load(f)
        data['accuracy'] = accuracy
        data['model_type'] = model_type
        data['language_code'] = language_code
        data['language_name'] = language_name
        data['dataset_name'] = dataset_name
        data['trained_at'] = datetime.utcnow().isoformat() + 'Z'
        with open(output_file, 'wb') as f:
            pickle.dump(data, f)
    else:
        model_data = {
            'model': model,
            'classes': class_names,
            'version': '2.0',
            'accuracy': accuracy,
            'model_type': model_type,
            'language_code': language_code,
            'language_name': language_name,
            'dataset_name': dataset_name,
            'trained_at': datetime.utcnow().isoformat() + 'Z',
        }
        with open(output_file, 'wb') as f:
            pickle.dump(model_data, f)

    print(f"\nModel saved to {output_file}")
    file_size = output_file.stat().st_size
    print(f"Model size: {file_size / (1024*1024):.2f} MB")


def main():
    """Main function."""
    args = parse_args()

    print("="*50)
    print("ASL Model Training")
    print("="*50)
    print(f"Input:       {args.input}")
    print(f"Output:      {args.output}")
    print(f"Model type:  {args.model_type}")
    if args.model_type == 'random_forest':
        print(f"Estimators:  {args.n_estimators}")
        print(f"Max depth:   {args.max_depth}")
    else:
        print(f"MLP layers:  {args.mlp_hidden_layers}")
        print(f"Max iter:    {args.mlp_max_iter}")
    print(f"Test size:   {args.test_size}")
    print(f"CV folds:    {args.cv_folds}")
    print(f"Augment:     {args.augment}")
    print()

    # Set random seed
    np.random.seed(args.random_seed)

    # Load dataset
    print("Loading dataset...")
    X, y, class_names = load_dataset(args.input)
    manifest = load_dataset_manifest(args.input) or {}

    language_code = (args.language_code or manifest.get('language_code') or 'ASL').upper()
    language_name = args.language_name or manifest.get('language_name') or 'American Sign Language'
    dataset_name = manifest.get('dataset_name') or Path(args.input).name

    print(f"\nDataset loaded:")
    print(f"  Total samples:    {len(X)}")
    print(f"  Feature dimension: {X.shape[1]}")
    print(f"  Number of classes: {len(class_names)}")
    print(f"  Language:         {language_code} ({language_name})")
    print(f"  Dataset name:     {dataset_name}")
    print(f"  Classes: {class_names}")

    # Optional K-fold cross-validation (on the full dataset before splitting)
    cv_results = None
    if args.cv_folds > 1:
        # Parse MLP hidden layers
        mlp_layers = parse_mlp_hidden_layers(args.mlp_hidden_layers)
        cv_results = run_cross_validation(
            X, y,
            model_type=args.model_type,
            cv_folds=args.cv_folds,
            random_seed=args.random_seed,
            n_estimators=args.n_estimators,
            max_depth=args.max_depth,
            hidden_layer_sizes=mlp_layers,
            max_iter=args.mlp_max_iter,
        )

    # Split data
    print(f"\nSplitting data (test={args.test_size})...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=args.test_size,
        random_state=args.random_seed,
        stratify=y
    )

    print(f"  Training samples: {len(X_train)}")
    print(f"  Test samples:     {len(X_test)}")

    # Optional data augmentation (only on training split)
    feature_extractor = FeatureExtractor()
    if args.augment:
        X_train, y_train = augment_training_data(
            X_train, y_train,
            feature_extractor=feature_extractor,
            num_augmentations=args.augment_factor,
            rotation_range=args.augment_rotation,
            noise_std=args.augment_noise,
            random_seed=args.random_seed,
        )

    # Train model
    mlp_layers = parse_mlp_hidden_layers(args.mlp_hidden_layers)
    if args.model_type == 'mlp':
        model = train_mlp(
            X_train, y_train,
            hidden_layer_sizes=mlp_layers,
            max_iter=args.mlp_max_iter,
            random_seed=args.random_seed,
        )
    else:
        model = train_random_forest(
            X_train, y_train,
            n_estimators=args.n_estimators,
            max_depth=args.max_depth,
            random_seed=args.random_seed,
        )

    # Evaluate model
    metrics = evaluate_model(
        model, X_test, y_test, class_names, args.cv_folds
    )

    # Save model
    save_model(
        model,
        class_names,
        args.output,
        accuracy=metrics['accuracy'],
        model_type=args.model_type,
        language_code=language_code,
        language_name=language_name,
        dataset_name=dataset_name,
    )

    print("\n" + "="*50)
    print("TRAINING COMPLETE")
    print("="*50)

    if cv_results:
        print(
            f"CV Accuracy: {cv_results['mean_accuracy']*100:.2f}% "
            f"± {cv_results['std_accuracy']*100:.2f}%"
        )

    # Print target accuracy check
    if metrics['accuracy'] >= 0.95:
        print(f"✓ Target achieved: {metrics['accuracy']*100:.2f}% >= 95%")
    else:
        print(f"✗ Target not met: {metrics['accuracy']*100:.2f}% < 95%")
        print("  Suggestions:")
        if args.model_type == 'random_forest':
            print("  - Increase n_estimators (e.g., 500)")
            print("  - Increase max_depth")
            print("  - Try --model-type mlp")
        else:
            print("  - Increase --mlp-max-iter")
            print("  - Try larger hidden layers, e.g. --mlp-hidden-layers 512,256,128")
        print("  - Add more training data")
        print("  - Use --augment to enable data augmentation")


if __name__ == '__main__':
    main()
